### ISSUE TITLE
Crash when granting permission with Shizuku on Android 12

### ISSUE THREAD

**Issue by sds100** [keymapperorg/KeyMapper#1001]
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name if not a very quick fix.
- [ ] write tests. put issue number in comment
- [ ] update documentation
- [ ] squash and merge
- [ ] delete branch

```
java.lang.NoSuchMethodError: No interface method grantRuntimePermission(Ljava/lang/String;Ljava/lang/String;I)V in class Landroid/content/pm/IPackageManager; or its super classes (declaration of 'android.content.pm.IPackageManager' appears in /system/framework/framework.jar)
        at io.github.sds100.keymapper.system.apps.AndroidPackageManagerAdapter.grantPermission(AndroidPackageManagerAdapter.kt:232)
        at io.github.sds100.keymapper.system.permissions.AutoGrantPermissionController$start$1.invokeSuspend(AutoGrantPermissionController.kt:31)
        at io.github.sds100.keymapper.system.permissions.AutoGrantPermissionController$start$1.invoke(Unknown Source:15)
        at io.github.sds100.keymapper.system.permissions.AutoGrantPermissionController$start$1.invoke(Unknown Source:24)
```

**Comment by sds100** [comment]
fixed
