### ISSUE TITLE
Crash when disabling accessibility service through notification

### ISSUE THREAD

**Issue by sds100** [keymapperorg/KeyMapper#1052]
**Developer TODO (don't remove)**
- [x] create new branch. put issue number at start of name if not a very quick fix.
- [x] write tests. put issue number in comment
- [x] update documentation
- [x] merge and delete branch (don't squash because want commit history to see why I made changes)

**Discord message link/email recipient**

**Describe the bug**
Disable the accessibility service using the notification.

Only be Android Lollipop - Marshmallow because the `disableSelf` method is not implemented.

```
java.lang.AbstractMethodError: abstract method "void io.github.sds100.keymapper.system.accessibility.IAccessibilityService.disableSelf()"
        at io.github.sds100.keymapper.system.accessibility.AccessibilityServiceController.onEventFromUi(AccessibilityServiceController.kt:445)
        at io.github.sds100.keymapper.system.accessibility.AccessibilityServiceController.access$onEventFromUi(AccessibilityServiceController.kt:40)
        at io.github.sds100.keymapper.system.accessibility.AccessibilityServiceController$7.invokeSuspend(AccessibilityServiceController.kt:198)
        at io.github.sds100.keymapper.system.accessibility.AccessibilityServiceController$7.invoke(AccessibilityServiceController.kt)
        at io.github.sds100.keymapper.system.accessibility.AccessibilityServiceController$7.invoke(AccessibilityServiceController.kt)
        at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1$2.emit(Collect.kt:136)
        at kotlinx.coroutines.flow.SharedFlowImpl.collect(SharedFlow.kt:351)
        at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend(SharedFlow.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:234)
        at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:190)
        at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:161)
        at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:328)
        at kotlinx.coroutines.flow.SharedFlowImpl.emitSuspend(SharedFlow.kt:472)
        at kotlinx.coroutines.flow.SharedFlowImpl.emit(SharedFlow.kt:374)
        at io.github.sds100.keymapper.system.accessibility.AccessibilityServiceAdapter$send$2.invokeSuspend(AccessibilityServiceAdapter.kt:86)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by sds100** [comment]
fixed
